# Generated by Django 2.0.4 on 2018-04-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('custUserID', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('subItem', models.CharField(max_length=64)),
                ('priceSmall', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priceLarge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderSize', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10)),
                ('orderPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('orderQty', models.IntegerField()),
                ('orderCost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='custOrders', to='orders.Order'),
        ),
    ]
