# Generated by Django 2.0.4 on 2018-04-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderSize',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=10),
        ),
    ]
