# Generated by Django 2.0.4 on 2018-04-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180422_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppingschosen', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderSize',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10),
        ),
    ]
