# Generated by Django 2.0.4 on 2018-04-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180423_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_subItem',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_toppings',
            field=models.ManyToManyField(blank=True, related_name='toppingsorder', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppingsmenu', to='orders.Topping'),
        ),
    ]
