# Generated by Django 2.0.4 on 2018-04-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='order_toppings',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
